# Generated by Django 5.0 on 2024-02-27 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('furniture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='furniture.furniture')),
            ],
        ),
    ]
