# Generated by Django 5.0 on 2024-02-27 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('furniture', '0002_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('6', 'six month'), ('12', '12 months'), ('18', '18 months'), ('24', '24 months'), ('undetermined', 'undetermined')], default='undetermined', max_length=255)),
                ('wage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='furniture.furniture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
