# Generated by Django 5.0 on 2024-04-08 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='renting_starts_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
